// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvu7ADloz7DR03etRYzbgcK_foqyAclE8',
    appId: '1:981439796060:android:9b96be3f4b4146a794a799',
    messagingSenderId: '981439796060',
    projectId: 'auvnet-ecommerce',
    storageBucket: 'auvnet-ecommerce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJKe4SN3wd3JdOHa3vY94Fy90_Ibqk1wo',
    appId: '1:981439796060:ios:ea80a3b0017f00ab94a799',
    messagingSenderId: '981439796060',
    projectId: 'auvnet-ecommerce',
    storageBucket: 'auvnet-ecommerce.firebasestorage.app',
    iosBundleId: 'com.example.auvnetFlutterInternshipAssessment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJKe4SN3wd3JdOHa3vY94Fy90_Ibqk1wo',
    appId: '1:981439796060:ios:ea80a3b0017f00ab94a799',
    messagingSenderId: '981439796060',
    projectId: 'auvnet-ecommerce',
    storageBucket: 'auvnet-ecommerce.firebasestorage.app',
    iosBundleId: 'com.example.auvnetFlutterInternshipAssessment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4rtXHscgmsSlGfPGP48phqKkB0mYGrFY',
    appId: '1:981439796060:web:e4d7d30f401bbd8a94a799',
    messagingSenderId: '981439796060',
    projectId: 'auvnet-ecommerce',
    authDomain: 'auvnet-ecommerce.firebaseapp.com',
    storageBucket: 'auvnet-ecommerce.firebasestorage.app',
    measurementId: 'G-BYB84P95B6',
  );

}